In [32]:
import numpy as np
import pandas as pd

mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [33]:
print(f"matriks1D :\n {mat1D}")
print(f"matriks1D indeks ke 7 :{mat1D[7]}")
print(f"matriks1D * 10 : {mat1D * 10}")

matriks1D :
 [1 2 3 4 5 6 7 8 9]
matriks1D indeks ke 7 :8
matriks1D * 10 : [10 20 30 40 50 60 70 80 90]


In [34]:
print(f"matriks2D :\n {mat2D}")
print(f"matriks2D * 10 :\n {mat2D * 10}")

matriks2D :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matriks2D * 10 :
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [35]:
print(mat1D.shape)
print(mat2D.shape)


(9,)
(3, 3)


In [36]:
print(mat1D.size)
print(mat2D.size)

9
9


In [37]:
mzero = np.zeros((3,3))
mone = np.ones((1000,1000))
mfull = np.full((4,4),7)
print(mzero)
print(mone)
print(mfull)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [38]:
data= np.array([[1,2,3],[4,5,6,],[7,8,9]])
ms = data.reshape((9,1))
mf = data.flatten()

print(data)
print(ms)
print(mf)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [40]:
jmld = 1000
gender = np.random.choice(["man","woman"],size = jmld)
transaksi = np.random.randint(0, 51, size=jmld) 
bayar = np.random.choice(["buruk", "sedang", "baik"], size=jmld)
usia = np.random.randint(12, 61, size=jmld)
df= pd.DataFrame({
    'gender': gender,
    'transaksi': transaksi,
    'bayar': bayar,
    'usia': usia
print("\nDataFrame (5 teratas):")
print(df.head())
})

SyntaxError: invalid syntax (814128428.py, line 11)